query createOverlaysNXTheme($layout: Upload!, $piece: Upload) {
	createOverlaysNXTheme(layout: $layout, piece: $piece) {
		filename
		data
		mimetype
	}
}

query createOverlay($blackImg: Upload!, $whiteImg: Upload!) {
	createOverlay(blackImg: $blackImg, whiteImg: $whiteImg) {
        filename
		data
		mimetype
	}
}