mutation createOverlaysNXTheme($layout: Upload!) {
	createOverlaysNXTheme(layout: $layout) {
		filename
		data
		mimetype
	}
}

mutation createOverlay($themeName: String, $blackImg: Upload!, $whiteImg: Upload!) {
	createOverlay(themeName: $themeName, blackImg: $blackImg, whiteImg: $whiteImg) {
        filename
		data
		mimetype
	}
}