query me {
	me {
		id
		display_name
		custom_username
		discord_user {
			discriminator
			avatar
		}
		bio
		joined
		role
		banner_image
		logo_image
		profile_color
		like_count
	}
}

query creator($id: String!) {
	creator(id: $id) {
		id
		display_name
		custom_username
		discord_user {
			discriminator
			avatar
		}
		bio
		joined
		role
		banner_image
		logo_image
		profile_color
		like_count
	}
}


mutation updateAuth($accepts: Boolean) {
	updateAuth(accepts: $accepts) {
		has_accepted
		backup_code
	}
}

mutation restoreAccount($creator_id: String!, $backup_code: String!) {
	restoreAccount(creator_id: $creator_id, backup_code: $backup_code)
}

mutation updateProfile(
	$custom_username: String
	$bio: String
	$profile_color: String
	$banner_image: Upload
	$logo_image: Upload
	$clear_banner_image: Boolean
	$clear_logo_image: Boolean
) {
	updateProfile(
		custom_username: $custom_username
		bio: $bio
		profile_color: $profile_color
		banner_image: $banner_image
		logo_image: $logo_image
		clear_banner_image: $clear_banner_image
		clear_logo_image: $clear_logo_image
	)
}
