query allCategories {
    categories
}

query allLayouts($target: String) {
    layoutList(target: $target) {
        id
        creator {
            id
            display_name
        }
        details {
            name
        }
    }
}

query allPacks($creators: [String!], $nsfw: Boolean) {
    packList(creators: $creators, nsfw: $nsfw) {
        id
        creator {
            id
            display_name
        }
        categories
        details {
            name
        }
    }
}
