query allCategories {
    categories
}

query allLayouts($target: String) {
    layoutList(target: $target) {
        id
        creator {
            id
            display_name
        }
        details {
            name
        }
    }
}
