query layout($name: String!, $menu: String!) {
	layout(name: $name, menu: $menu) {
		uuid
		details {
			name
			uuid
			author {
				name
				discordTag
			}
			description
			color
			version
		}
		menu
		last_updated
		baselayout
		has_pieces
		pieces {
			name
			values {
				value
				image
				json
			}
		}
	}
}

query layoutDetails($name: String!, $menu: String!) {
	layout(name: $name, menu: $menu) {
		uuid
		details {
			name
			uuid
			author {
				name
				discordTag
			}
			description
			color
			version
		}
		menu
		last_updated
		has_pieces
	}
}

query layoutsList($menu: String!) {
	layoutsList(menu: $menu) {
		uuid
		details {
			name
			uuid
			author {
				name
				discordTag
			}
			description
			color
			version
		}
		menu
		last_updated
	}
}
