query layout($name: String!, $menu: String!) {
	layout(name: $name, menu: $menu) {
		uuid
		details {
			name
			uuid
			author {
				name
				discordTag
			}
			description
			color
			version
		}
		menu
		last_updated
		baselayout
	}
}

query layoutsList($menu: String!) {
	layoutsList(menu: $menu) {
		uuid
		details {
			name
			uuid
			author {
				name
				discordTag
			}
			description
			color
			version
		},
		menu
		last_updated
	}
}

