query layout($id: Int!, $target: String!) {
	layout(id: $id, target: $target) {
		uuid
		id
		details {
			name
			author {
				name
				discord_tag
			}
			description
			color
			version
		}
		target
		last_updated
		baselayout
		has_pieces
		pieces {
			name
			values {
				value
				image
				uuid
				json
			}
		}
		commonlayout
	}
}

query layoutDetails($id: Int!, $target: String!) {
	layout(id: $id, target: $target) {
		uuid
		id
		details {
			name
			author {
				name
				discord_tag
			}
			description
			color
			version
		}
		target
		last_updated
		has_pieces
		commonlayout
	}
}

query layoutsList($target: String!) {
	layoutsList(target: $target) {
		uuid
		id
		details {
			name
			author {
				name
				discord_tag
			}
			description
			color
			version
		}
		target
		last_updated
	}
}
