query pack($id: String!) {
	pack(id: $id) {
		id
		creator {
			id
			discord_user {
				username
			}
		}
		details {
			name
			description
			version
		}
		last_updated
		categories
		dl_count
		like_count
		themes {
			id
			id
			details {
				name
			}
			target
		}
	}
}

query rowPacksList($creator_id: String, $limit: Int) {
	packsList(creator_id: $creator_id, limit: $limit) {
		id
		creator {
			id
			discord_user {
				username
			}
		}
		details {
			name
		}
		last_updated
		themes {
			id
			layout {
				id
			}
		}
	}
}

query packsList {
	packsList {
		id
		creator {
			id
			discord_user {
				username
			}
		}
		details {
			name
			description
			version
		}
		last_updated
		categories
		dl_count
		like_count
		themes {
			id
			layout {
				details {
					name
				}
			}
		}
	}
}

query downloadPack($id: String!) {
	downloadPack(id: $id) {
		filename
		data
		mimetype
	}
}