query pack($id: Int!) {
	pack(id: $id) {
		uuid
		id
		creator {
			id
			discord_user {
				username
			}
		}
		details {
			name
			description
			version
		}
		last_updated
		categories
		dl_count
		like_count
		themes {
			id
			details {
				name
			}
			target
		}
	}
}

query rowPacksList($creator_id: String, $limit: Int) {
	packsList(creator_id: $creator_id, limit: $limit) {
		uuid
		id
		creator {
			id
			discord_user {
				username
			}
		}
		details {
			name
		}
		last_updated
		themes {
			uuid
			layout {
				uuid
			}
		}
	}
}

query packsList {
	packsList {
		uuid
		id
		creator {
			id
			discord_user {
				username
			}
		}
		details {
			name
			description
			version
		}
		last_updated
		categories
		dl_count
		like_count
		themes {
			uuid
		}
	}
}

mutation downloadPack($uuid: GUID!) {
	downloadPack(uuid: $uuid) {
		filename
		data
		mimetype
	}
}