query allCreators($target: String) {
    themeList(target: $target) {
        creator {
			id
			display_name
		}
    }
}

query allLayouts($target: String) {
    themeList(target: $target) {
        layout {
			id
			details {
				name
			}
		}
    }
}

query theme($id: String!) {
	theme(id: $id) {
		id
		creator {
			id
			display_name
		}
		details {
			name
			description
			version
		}
        layout {
			id
            details {
                name
            }
			target
        }
        pack {
			id
            details {
                name
            }
        }
		last_updated
		pieces {
            name
			value {
				value
				uuid
			}
        }
		target
        categories
		dl_count
		like_count
		bg_type
	}
}

query rowThemeList($target: String, $limit: Int, $page: Int, $query: String, $sort: String, $order: String, $creators: [String!], $layouts: [String!], $nsfw: Boolean) {
	themeList(target: $target, limit: $limit, page: $page, query: $query, sort: $sort, order: $order, creators: $creators, layouts: $layouts, nsfw: $nsfw) {
		id
		creator {
			id
			display_name
		}
		layout {
			id
			details {
				name
			}
		}
		details {
			name
		}
		target
		last_updated
	}
}

query themeList($hash: String!, $target: String, $limit: Int, $page: Int, $query: String, $sort: String, $order: String, $creators: [String!], $layouts: [String!], $nsfw: Boolean) {
	themeList(target: $target, limit: $limit, page: $page, query: $query, sort: $sort, order: $order, creators: $creators, layouts: $layouts, nsfw: $nsfw) {
		id
		creator {
			id
			display_name
		}
		layout {
			id
			uuid
			details {
				name
			}
		}
		details {
			name
			description
			version
		}
		target
		last_updated
		categories
		dl_count
		like_count
	}

	pagination(hash: $hash) {
		page
		limit
		page_count
		item_count
	}
}

query downloadTheme($id: String!, $piece_uuids: [GUID!]) {
	downloadTheme(id: $id, piece_uuids: $piece_uuids) {
		filename
		url
		mimetype
	}
}