query allCreators($target: String, $nsfw: Boolean) {
    themeList(target: $target, nsfw: $nsfw) {
        layout {
            id
        }
        creator {
            id
            display_name
        }
    }
}

query allLayouts($target: String, $nsfw: Boolean) {
    themeList(target: $target, nsfw: $nsfw) {
        layout {
            id
            details {
                name
            }
        }
    }
}

query theme($id: String!) {
    theme(id: $id) {
        id
        creator {
            id
            display_name
        }
        details {
            name
            description
            version
        }
        layout {
            id
            details {
                name
            }
            target
        }
        pack {
            id
            details {
                name
            }
            categories
        }
        last_updated
        pieces {
            name
            value {
                value
                uuid
            }
        }
        target
        categories
        dl_count
        like_count
        bg_type
        preview {
            original
            thumb
        }
    }
}

query rowThemeList($target: String, $limit: Int, $page: Int, $query: String, $sort: String, $order: String, $creators: [String!], $layouts: [String!], $nsfw: Boolean) {
    themeList(target: $target, limit: $limit, page: $page, query: $query, sort: $sort, order: $order, creators: $creators, layouts: $layouts, nsfw: $nsfw) {
        id
        creator {
            id
            display_name
        }
        layout {
            id
            details {
                name
            }
        }
        categories
        details {
            name
        }
        target
        last_updated
        preview {
            thumb
        }
    }
}

query themeList($hash: String!, $target: String, $limit: Int, $page: Int, $query: String, $sort: String, $order: String, $creators: [String!], $layouts: [String!], $nsfw: Boolean) {
    themeList(target: $target, limit: $limit, page: $page, query: $query, sort: $sort, order: $order, creators: $creators, layouts: $layouts, nsfw: $nsfw) {
        id
        creator {
            id
            display_name
        }
        layout {
            id
            uuid
            details {
                name
            }
        }
        details {
            name
            description
            version
        }
        target
        last_updated
        categories
        dl_count
        like_count
        preview {
            thumb
        }
    }

    pagination(hash: $hash) {
        page
        limit
        page_count
        item_count
    }
}

query randomThemeIDs($limit: Int) {
    randomThemeIDs(limit: $limit)
}

query downloadTheme($id: String!, $piece_uuids: [GUID!]) {
    downloadTheme(id: $id, piece_uuids: $piece_uuids) {
        filename
        url
        mimetype
    }
}

mutation deleteTheme($id: String!) {
    deleteTheme(id: $id)
}

mutation updateTheme($id: String!, $file: Upload, $name: String!, $layout_id: String, $pack_id: String, $used_pieces: [UsedPieceInput!], $description: String, $version: String!, $categories: [String!], $nsfw: Boolean) {
    updateTheme(id: $id, file: $file, name: $name, layout_id: $layout_id, pack_id: $pack_id, used_pieces: $used_pieces, description: $description, version: $version, categories: $categories, nsfw: $nsfw)
}
