query theme($id: Int!, $target: String!) {
	theme(id: $id, target: $target) {
		uuid
		id
		details {
			name
			author {
				name
				discord_tag
			}
			description
			color
			version
		}
        layout {
            uuid
			id
            details {
                name
                author {
                    name
                }
            }
			target
        }
        pack {
            uuid
			id
            details {
                name
                author {
                    name
                    discord_tag
                }
                description
                color
                version
            }
            last_updated
        }
		last_updated
		pieces {
            name
			value {
				value
				uuid
			}
        }
		target
        categories
		dl_count
		bg_type
	}
}

query themeDetails($id: Int!, $target: String!) {
	themeDetails(id: $id, target: $target) {
		uuid
		id
		details {
			name
			author {
				name
				discord_tag
			}
			description
			color
			version
		}
		last_updated
		pieces {
            name
			value {
				value
				uuid
			}
        }
        categories
		dl_count
		bg_type
	}
}

query themesList($target: String!) {
	themesList(target: $target) {
		uuid
		id
		details {
			name
			author {
				name
			}
			description
			color
			version
		}
		last_updated
		categories
		dl_count
	}
}

mutation downloadTheme($uuid: GUID!, $piece_uuids: [GUID!]) {
	downloadTheme(uuid: $uuid, piece_uuids: $piece_uuids) {
		filename
		data
		mimetype
	}
}